return {
	require("plugins.themes.tokyonight"),
	require("plugins.themes.onedark"),
	-- require("plugins.themes.doki-theme"),
	require("plugins.themes.cyberdream"),
	require("plugins.themes.rose"),
	require("plugins.themes.kanagawa"),
	require("plugins.themes.material"),
	require("plugins.themes.dracula"),
	require("plugins.themes.synthweave"),
	require("plugins.themes.nightfox"),
	require("plugins.themes.starry"),
	require("plugins.themes.catppuccin"),
	require("plugins.themes.colorbuddy"),
	require("plugins.themes.calvera-dark"),
	require("plugins.themes.zephyr"),
	require("plugins.themes.sonokai"),
	require("plugins.themes.nyoom"),
	require("plugins.themes.sweetie"),
	require("plugins.themes.fluoromachine"),
	require("plugins.themes.eldritch"),
	require("plugins.themes.bluloco"),
	require("plugins.themes.embark"),
	require("plugins.themes.iceberg"),
	require("plugins.themes.github"),
	require("plugins.themes.gruvbox"),
}
