return {
	require("plugins.themes.tokyonight"),
	require("plugins.themes.onedark"),
	require("plugins.themes.doki-theme"),
	require("plugins.themes.cyberdream"),
	require("plugins.themes.rose"),
	require("plugins.themes.kanagawa"),
	require("plugins.themes.material"),
	require("plugins.themes.dracula"),
	require("plugins.themes.synthweave"),
	require("plugins.themes.nightfox"),
	require("plugins.themes.starry"),
	require("plugins.themes.catppuccin"),
	require("plugins.themes.colorbuddy"),
	require("plugins.themes.calvera-dark"),
	require("plugins.themes.zephyr"),
}
